\input texinfo   @c -*-texinfo-*-
@c %**start of header
@setfilename oln-ref.info
@settitle Olena Reference Manual
@setchapternewpage odd
@afourpaper
@c %**end of header
@include version.texi

@synindex fn cp
@synindex vr cp

@c Gross hack.  We use double-colon a lot in this manual, because
@c we describe C++ functions organized into namespace.
@c
@c Espcially we want to put `::' in node names.  This is asking for
@c trouble.  There are several issues:
@c  - makeinfo will fail to parse in any colon in the node name of
@c    a menu entry.  This is solved by using `@value{dc}' instead of
@c    `::' when naming a node.
@c  - info does not support `::' in a node name, because these
@c    characters mark the end of an hyperlink.  So when outputing
@c    info files, we replace `@value{dc}' by a single point `.'.
@c    In other format, we use a double colon.
@ifinfo
@set dc .
@end ifinfo
@ifnotinfo
@set dc ::
@end ifnotinfo


@ifinfo
This file documents Olena, a generic image processing library.

Copyright 2001  Laboratoire de Recherche et D@'eveloppement de l'@'Epita.

Permission is granted to make and distribute verbatim
copies of this manual provided the copyright notice and
this permission notice are preserved on all copies.

@ignore
Permission is granted to process this file through TeX
and print the results, provided the printed document
carries a copying permission notice identical to this
one except for the removal of this paragraph (this
paragraph not being relevant to the printed manual).

@end ignore
Permission is granted to copy and distribute modified versions of this
manual under the conditions for verbatim copying, provided that the
entire resulting derived work is distributed under the terms of a
permission notice identical to this one.

Permission is granted to copy and distribute
translations of this manual into another language,
under the above conditions for modified versions,
except that this permission notice may be stated in a
translation approved by the Free Software Foundation.
@end ifinfo


@titlepage
@title Olena Reference Manual
@subtitle A generic image processing library.
@c @subtitle Version @value{EDITION}, @value{UPDATED}

@page
@vskip 0pt plus 1filll
Copyright @copyright{} 2001
Laboratoire de Recherche et D@'eveloppement de l'@'Epita.

Permission is granted to make and distribute verbatim
copies of this manual provided the copyright notice and
this permission notice are preserved on all copies.

Permission is granted to copy and distribute modified versions of this
manual under the conditions for verbatim copying, provided that the
entire resulting derived work is distributed under the terms of a
permission notice identical to this one.

Permission is granted to copy and distribute
translations of this manual into another language,
under the above conditions for modified versions,
except that this permission notice may be stated in a
translation approved by the Free Software Foundation.
@end titlepage

@node Top, Morphological processings, ,

@ifinfo
This document describes Olena, a generic image processing library.

@c This document applies to version @value{VERSION}.
@end ifinfo

@contents

@menu
* Morphological processings::
* Index::
@end menu

@c ======================================================================
@node    Morphological processings, Index, Top, Top
@comment node-name,     next,           previous, up
@chapter Morphological processings

@raisesections
@include ref-morpho.texi
@lowersections

@c ======================================================================
@node Index, , Morphological processings, Top
@unnumbered Index
@printindex cp
@bye
