2:
	g++ -W -Wall -Werror -ansi -pedantic -I$(HOME)/olena_1/metalic main2.cc -o atelier

all:
	g++ -W -Wall -Werror -ansi -pedantic -I$(HOME)/olena_1/metalic main.cc -o j1

hard:
	/lrde/dev/linux-x86/intel/icc9.1/bin/icpc -W -Wall -Werror -ansi -pedantic -I$(HOME)/olena_1/metalic main.cc -o atelier
