CC=g++


2:
	$(CC) -W -Wall -Werror -ansi -pedantic -I$(HOME)/olena_1/metalic main2.cc -o atelier

3:
	$(CC) -W -Wall -Werror -ansi -pedantic -I$(HOME)/olena_1/metalic main3.cc -o atelier

1:
	$(CC) -W -Wall -Werror -ansi -pedantic -I$(HOME)/olena_1/metalic main.cc -o atelier

hard3:
	/lrde/dev/linux-x86/intel/icc9.1/bin/icpc -W -Wall -Werror -ansi -pedantic -I$(HOME)/olena_1/metalic main3.cc -o atelier
