# -*- Makefile -*-

# Don't use -ansi because it prevents us from using functions
# like `remove' or `mkstemp' with g++-2.95.x.
AM_CXXFLAGS = $(OLN_CXXFLAGS) -Wall -W -pedantic
AM_CPPFLAGS = $(OLN_CPPFLAGS) -DRDATADIR=\"$(OLN_IMG_DIR)\" -DWDATADIR=\"$(top_builddir)/../img\" -I$(top_srcdir)/check
