@node Abstract
@chapter Abstract

This is the tenth public release of Olena, a generic image
processing library in C++.

@ifplaintext
Please read the files BUILD and INSTALL for information about building
and installing Olena.
@end ifplaintext

Olena is a project developed by the EPITA Research and Development
Laboratory (@url{http://www.lrde.epita.fr}) since 1997.  We did numerous
prototypes and throwaway experiments before settling into the kind of
programming paradigm which is finally here.

The documentation does not cover the whole project.  In the @file{doc/}
directory you will find the first draft of a reference manual.  It
only documents the image hierarchy and image processing algorithms.
In the @file{doc/demo/} directory lie a few sample programs.
The file @file{doc/demo/tour.cc} attempts to introduce you to the basics
of Olena.
For the rest, we're afraid you will have to dig the code or e-mail us.

Please direct any question or comments to @email{olena@@lrde.epita.fr},
or @email{olena-bugs@@lrde.epita.fr}.

Olena also has a web page, located at
@url{http://www.lrde.epita.fr/cgi-bin/twiki/view/Projects/Olena}.
