@documentencoding ISO-8859-1

@node Acknowledgements
@section Acknowledgements

The following people contributed to Olena, maybe indirectly through
one of the numerous prototypes Olena has uprisen from. Olena would not
be what it is today without their work.

@table @sc
@item Thierry G@'eraud
@itemize @minus
@item management of the project in the first place,
@item type system,
@item numerous hours spent thinking about Olena.
@end itemize

@item Alexandre Duret-Lutz
@itemize @minus
@item maintenance of the source tree for several years,
@item type system,
@item test system,
@item first documentation system,
@item numerous hours spent on Olena to make it better.
@end itemize

@item Reda Dehak
@itemize @minus
@item management of the project,
@item color conversions,
@item cleanup the sources.
@end itemize

@item Akim Demaille
@itemize @minus
@item configuration system.
@item maintenance of code's clearness.
@end itemize

@item Anthony Pinagot
@itemize @minus
@item Olena I/O,
@item statistical operators,
@item FFT algorithm.
@end itemize

@item Astrid Wang
@itemize @minus
@item new documentation system,
@item static arrays implementation.
@end itemize

@item Damien Thivolle
@itemize @minus
@item contributions to document the code,
@item generic morphers,
@item configuration system.
@end itemize

@item David Lesage
@itemize @minus
@item type system,
@item new paradigm,
@item cleanup the sources.
@end itemize

@item Dimitri Papadopoulos-Orfanos
@itemize @minus
@item  type system
@end itemize


@item Emmanuel Turquin
@itemize @minus
@item implementation of transforms,
@item integre.
@end itemize

@item Giovanni Palma
@itemize @minus
@item color conversion,
@item attribute opening and closing algorithms,
@item new documentation system,
@item document the code,
@item cleanup the sources.
@end itemize

@item Heru Xue
@itemize @minus
@item color system.
@end itemize

@item Ignacy Gawedzki
@itemize @minus
@item color system.
@end itemize


@item Jean Chalard
@itemize @minus
@item colors,
@item vectors and matrices implementation,
@item Olena iterators implementation,
@item wavelets.
@end itemize

@item Jean-S@'ebastien Mouret
@itemize @minus
@item image I/O,
@item source tree and configuration system,
@item fast morphological operators.
@end itemize

@item J@'er@^ome Darbon
@itemize @minus
@item image morphology and Olena morpho.
@end itemize

@item Ludovic Perrine
@itemize @minus
@item fuzzy types.
@end itemize

@item Micha@"el Strauss
@itemize @minus
@item image morphology,
@item watershed algorithms,
@item Olena I/O.
@end itemize

@item Nicolas Burrus
@itemize @minus
@item integre,
@item Olena I/O,
@item source tree.
@end itemize

@item Niels van Vliet
@itemize @minus
@item color conversion,
@item attribute opening and closing algorithms,
@item contributions to document the code,
@item histograms.
@end itemize

@item Pierre-Yves Strub
@itemize @minus
@item Olena morpho,
@item source tree and configuration system,
@item type system.
@end itemize

@item Qu@^oc Peyrot
@itemize @minus
@item watershed algorithm.
@end itemize

@item Rapha@"el Poss
@itemize @minus
@item source tree and configuration system,
@item documentation.
@end itemize

@item R@'emi Coupet
@itemize @minus
@item Olena morpho,
@item data types (pre-0.6),
@item Olena core,
@item bibliographic research.
@end itemize

@item Renaud Fran@,cois
@itemize @minus
@item bibliographic research.
@end itemize

@item Simon Odou
@itemize @minus
@item contributions to document the code,
@item generic morphers.
@end itemize

@item Sylvain Berlemont
@itemize @minus
@item combinatorial maps,
@item cleanup the sources.
@end itemize

@item Yann R@'egis-Gianas
@itemize @minus
@item type system.
@end itemize

@item Yoann Fabre
@itemize @minus
@item type system.
@end itemize


@item Vincent Berruchon

@end table

@sp 2

In addition, we would like to thank EPITA and its user groups EpX and
Prologin for giving us access to Solaris, FreeBSD, NetBSD, OpenBSD and
CygWin machines.
