#! /bin/sh

[ -d "$1" -a -f "$1/expand.sh" -a -f "$1/ChangeLog" ] || \
  { echo "usage: $0 <swilena srcdir>" >&2; exit 1; }

SWILENA=`cd $1 && pwd`

mkdir -p "$SWILENA/src"
mkdir -p "$SWILENA/python"
mkdir -p "$SWILENA/ruby"

MODULES="$MODULES ntg"
for dim in 1 2 3; do

  ## {1d,2d,3d} families
  for mod in point structelt w_win imagesize image; do
     cat >"$SWILENA/src/swilena_$mod${dim}d.i" <<EOF
// Warning: this file was generated by expand.sh
%module swilena_$mod${dim}d
%include swilena_$mod.i
decl_$mod($dim)
EOF
     MODULES="$MODULES ${mod}${dim}d"
  done

  ## w_window instances
  for t in int float; do
     echo "make_w_win(w_win${dim}d_$t, $dim, $t)" >>"$SWILENA/src/swilena_w_win${dim}d.i"
  done

  ## Image instances
  cat >>"$SWILENA/src/swilena_image${dim}d.i" <<EOF
%include swilena_ntg_macros.i
%import swilena_ntg.i
EOF
  # int_u8 int_u16 int_s8 int_s16 int_s8s int_s16s int_s32s
  # int_u8s int_u16s int_u32s
  # float_s rgb_8 rgb_16 rgb_32
  cat >> "$SWILENA/src/swilena_image${dim}d.i" <<EOF
make_image(image${dim}d_bin, $dim, ntg_bin, ntg_bin_value)
make_image(image${dim}d_u8, $dim, ntg_int_u8, ntg_int_u8_value)
make_image(image${dim}d_u32, $dim, ntg_int_u32, ntg_int_u32_value)
make_image(image${dim}d_s8, $dim, ntg_int_s8, ntg_int_s8_value)
make_image(image${dim}d_s32, $dim, ntg_int_s32, ntg_int_s32_value)
make_image(image${dim}d_float, $dim, ntg_float, ntg_float_value)
EOF

  TYPES="ntg_bin ntg_int_u8 ntg_int_u32 ntg_int_s8 ntg_int_s32 ntg_float"

  ## Morpho algorithms
  for types in $TYPES; do
      MODULES="$MODULES morpho${dim}d_${types}"
  done
  $SWILENA/generate_morpho_instantiations.py $SWILENA/src

  ## Arith
  MODULES="$MODULES arith${dim}d"
  $SWILENA/generate_arith_instantiations.py $SWILENA/src

  ## Conversions
  MODULES="$MODULES conversions${dim}d"
  $SWILENA/generate_conversions_instantiations.py $SWILENA/src
done # for dim ...

#################### Python stuff #######################

PYMODS=''
PYTHON=''

header_python()
{
cat <<EOF
## Include this file into your Makefile.am -*- Makefile -*-
##
## makefile.swig for swilena/python
## NOTE: this file was generated automatically by expand.sh
##

INCLUDES = \$(PYTHON_CPPFLAGS) -I\$(srcdir)/../src
AM_CPPFLAGS = -DOLN_EXCEPTIONS
AM_CXXFLAGS = \$(CXXFLAGS_OPTIMIZE)
AM_LDFLAGS = -shared -lswigpy \$(ZLIB_LDFLAGS)

EOF
}

dump_python()
{
    echo -n "pyexec_PROGRAMS ="
    ilist=0
    for mod in $MODULES; do
      if [ `expr $ilist % 4` = 0 ]; then
         echo " \\"; echo -ne "\t"
      fi
      echo -n " _swilena_$mod.so"
      ilist=`expr $ilist + 1`
    done
    echo; echo
    echo -n "python_PYTHON +="
    ilist=0
    for mod in $MODULES; do
      if [ `expr $ilist % 4` = 0 ]; then
         echo " \\"; echo -ne "\t"
      fi
      echo -n " swilena_$mod.py"
      ilist=`expr $ilist + 1`
    done
    echo; echo
    for mod in $MODULES; do
      echo "_swilena_${mod}_so_SOURCES = swilena_${mod}_wrap.cxx"
    done
    echo
    ilist=0
    for mod in $MODULES; do
      if [ -r "$SWILENA/src/swilena_${mod}.i" ]; then
         sdir=src
      else
         sdir=meta
      fi
      echo "swilena_${mod}_wrap.cxx swilena_${mod}.py: \$(srcdir)/../$sdir/swilena_${mod}.i"
      echo -e "\t\$(SWIG) -noruntime -c++ -python -I\$(srcdir)/../src -I\$(srcdir)/../meta \$(CPPFLAGS) -o swilena_${mod}_wrap.cxx \$(srcdir)/../$sdir/swilena_${mod}.i"
      echo
    done
}

#################### Ruby stuff #######################

header_ruby()
{
cat <<EOF
## Include this file in your Makefile.am -*- Makefile -*-
##
## makefile.swig for swilena/ruby
## NOTE: this file was generated automatically by expand.sh
##

INCLUDES = \$(RUBY_CPPFLAGS) -I\$(srcdir)/../src
AM_CPPFLAGS = -DOLN_EXCEPTIONS
AM_CXXFLAGS = \$(CXXFLAGS_OPTIMIZE)
AM_LDFLAGS = -shared -lswigrb \$(ZLIB_LDFLAGS)

EOF
}

dump_ruby()
{
    echo -n "ruby_PROGRAMS ="
    ilist=0
    for mod in $MODULES; do
      if [ `expr $ilist % 4` = 0 ]; then
         echo " \\"; echo -ne "\t"
      fi
      echo -n " swilena_$mod.so"
      ilist=`expr $ilist + 1`
    done
    echo; echo
    for mod in $MODULES; do
      echo "swilena_${mod}_so_SOURCES = swilena_${mod}_wrap.cxx"
    done
    echo
    ilist=0
    for mod in $MODULES; do
      if [ -r "$SWILENA/src/swilena_${mod}.i" ]; then
         sdir=src
      else
         sdir=meta
      fi
      echo "swilena_${mod}_wrap.cxx: \$(srcdir)/../$sdir/swilena_${mod}.i"
      echo -e "\t\$(SWIG) -c -c++ -ruby -I\$(srcdir)/../src -I\$(srcdir)/../meta \$(CPPFLAGS) -o swilena_${mod}_wrap.cxx \$(srcdir)/../$sdir/swilena_${mod}.i"
      echo
    done
}

############ Generic stuff ###########

header_src() {
    cat <<EOF
## Include this file in your Makefile.am
##
## makefile.swig for swilena/src
## NOTE: this file was generated automatically by expand.sh
##
EOF
}

dump_src() {
    echo -n "EXTRA_DIST ="
    ilist=0
    for mod in $MODULES; do
      if [ -r "$SWILENA/src/swilena_${mod}.i" ]; then
         if [ `expr $ilist % 4` = 0 ]; then
	    echo " \\"
            echo -ne "\t"
	 fi
	 echo -n " swilena_${mod}.i"
	 ilist=`expr $ilist + 1`
      fi
    done
    echo
}

############ Output ###############

header_src >"$SWILENA/src/makefile.swig"
dump_src >>"$SWILENA/src/makefile.swig"
header_python >"$SWILENA/python/makefile.swig"
dump_python >>"$SWILENA/python/makefile.swig"
header_ruby >"$SWILENA/ruby/makefile.swig"
dump_ruby >>"$SWILENA/ruby/makefile.swig"
