#! /bin/sh

# Copyright (C) 2005, 2009, 2010 EPITA Research and Development
# Laboratory (LRDE).
#
# This file is part of Olena.
#
# Olena is free software: you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free
# Software Foundation, version 2 of the License.
#
# Olena is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Olena.  If not, see <http://www.gnu.org/licenses/>.

# Failures do matter.
set -e
# Tell what's going on.
set -x

# Run autoreconf?
run_autoreconf_p=true

usage ()
{
  cat <<EOF
Usage: $0 [OPTION]

Options:
  -h, --help              display this message
      --no-autoreconf     do not run autoreconf

Report bugs to <olena-bugs@lrde.epita.fr>
EOF
}

# Process arguments.
for arg in "$@"; do
  case "$arg" in
    -h|--help) usage; exit 0 ;;
    --no-autoreconf) run_autoreconf_p=false ;;
    *) fatal "error: unrecognized option: $1" ;;
  esac
done

mkdir -p _config
touch _config/local-config.rb.in

libtoolize=libtoolize
for l in "$LIBTOOLIZE" glibtoolize libtoolize;
do
  if ($l --version) >/dev/null 2>&1; then
    libtoolize=$l
    break
  fi
done
export LIBTOOLIZE=$libtoolize
# Make the libtool with ltdl
"$libtoolize" --force --copy --automake --ltdl

if $run_autoreconf_p; then
  # Finally, install the GNU Build System.
  autoreconf -f -v -i
fi

# `autoreconf' wrongfully creates a directory named
# `libiberty/$libiberty_topdir' (containing an actual `$' sign)
# because Libiberty's `configure.ac' invokes `AC_CONFIG_AUX_DIR' with
# a shell variable as argument (`$libiberty_topdir'); remove this
# (presumably empty) directory.
if test -d 'libiberty/$libiberty_topdir'; then
  rmdir 'libiberty/$libiberty_topdir'
fi
