##
## List of headers in integre
## Include this file to have access to their name.
##

NTG_DEP =					\
  color/rgb_8.hh				\
  config/system.hh				\
  config/math.hh				\
  real/bin.hh					\
  real/int_u8.hh
