# -*- Makefile -*-

AM_CXXFLAGS = $(CXXFLAGS_OPTIMIZE) $(CXXFLAGS_STRICT_ERRORS)
AM_CPPFLAGS = -I$(top_srcdir)/metalic/tests/check -I$(top_srcdir)/olena/tests/check -I$(OLN_LOCAL_BUILD) -I$(OLN_LOCAL_SRC)
