# Provide missing recursive targets required by Automake, so that
# libiberty can be distributed with the hosting project.

# Have Makefile depend on this helper.
Makefile: $(srcdir)/local.mk


# Files to be distributed.
DISTFILES = $(srcdir)/ChangeLog $(srcdir)/README $(srcdir)/COPYING.LIB

# Source files.
#
# Files listed in `CFILES' are not prefixed by `$(srcdir)/'; use a
# replacement variable.
srcdir_CFILES =								\
  $(srcdir)/alloca.c $(srcdir)/argv.c $(srcdir)/asprintf.c		\
  $(srcdir)/atexit.c $(srcdir)/basename.c $(srcdir)/bcmp.c		\
  $(srcdir)/bcopy.c $(srcdir)/bsearch.c $(srcdir)/bzero.c		\
  $(srcdir)/calloc.c $(srcdir)/choose-temp.c $(srcdir)/clock.c		\
  $(srcdir)/concat.c $(srcdir)/cp-demangle.c $(srcdir)/cp-demint.c	\
  $(srcdir)/cplus-dem.c $(srcdir)/crc32.c $(srcdir)/dyn-string.c	\
  $(srcdir)/fdmatch.c $(srcdir)/ffs.c $(srcdir)/fibheap.c		\
  $(srcdir)/filename_cmp.c $(srcdir)/floatformat.c $(srcdir)/fnmatch.c	\
  $(srcdir)/fopen_unlocked.c $(srcdir)/getcwd.c $(srcdir)/getopt.c	\
  $(srcdir)/getopt1.c $(srcdir)/getpagesize.c $(srcdir)/getpwd.c	\
  $(srcdir)/getruntime.c $(srcdir)/gettimeofday.c $(srcdir)/hashtab.c	\
  $(srcdir)/hex.c $(srcdir)/index.c $(srcdir)/insque.c			\
  $(srcdir)/lbasename.c $(srcdir)/lrealpath.c				\
  $(srcdir)/make-relative-prefix.c $(srcdir)/make-temp-file.c		\
  $(srcdir)/md5.c $(srcdir)/memchr.c $(srcdir)/memcmp.c			\
  $(srcdir)/memcpy.c $(srcdir)/memmem.c $(srcdir)/memmove.c		\
  $(srcdir)/mempcpy.c $(srcdir)/memset.c $(srcdir)/mkstemps.c		\
  $(srcdir)/objalloc.c $(srcdir)/obstack.c $(srcdir)/partition.c	\
  $(srcdir)/pexecute.c $(srcdir)/pex-common.c $(srcdir)/pex-djgpp.c	\
  $(srcdir)/pex-msdos.c $(srcdir)/pex-one.c $(srcdir)/pex-unix.c	\
  $(srcdir)/pex-win32.c $(srcdir)/physmem.c $(srcdir)/putenv.c		\
  $(srcdir)/random.c $(srcdir)/regex.c $(srcdir)/rename.c		\
  $(srcdir)/rindex.c $(srcdir)/safe-ctype.c $(srcdir)/setenv.c		\
  $(srcdir)/setproctitle.c $(srcdir)/sha1.c $(srcdir)/sigsetmask.c	\
  $(srcdir)/snprintf.c $(srcdir)/sort.c $(srcdir)/spaces.c		\
  $(srcdir)/splay-tree.c $(srcdir)/stpcpy.c $(srcdir)/stpncpy.c		\
  $(srcdir)/strcasecmp.c $(srcdir)/strchr.c $(srcdir)/strdup.c		\
  $(srcdir)/strerror.c $(srcdir)/strncasecmp.c $(srcdir)/strncmp.c	\
  $(srcdir)/strrchr.c $(srcdir)/strsignal.c $(srcdir)/strstr.c		\
  $(srcdir)/strtod.c $(srcdir)/strtol.c $(srcdir)/strtoul.c		\
  $(srcdir)/strndup.c $(srcdir)/strverscmp.c $(srcdir)/tmpnam.c		\
  $(srcdir)/unlink-if-ordinary.c $(srcdir)/vasprintf.c			\
  $(srcdir)/vfork.c $(srcdir)/vfprintf.c $(srcdir)/vprintf.c		\
  $(srcdir)/vsnprintf.c $(srcdir)/vsprintf.c $(srcdir)/waitpid.c	\
  $(srcdir)/xatexit.c $(srcdir)/xexit.c $(srcdir)/xmalloc.c		\
  $(srcdir)/xmemdup.c $(srcdir)/xstrdup.c $(srcdir)/xstrerror.c		\
  $(srcdir)/xstrndup.c
DISTFILES += $(srcdir_CFILES) $(srcdir)/cp-demangle.h $(srcdir)/pex-common.h

# Configuration.
DISTFILES +=					\
  $(srcdir)/aclocal.m4				\
  $(srcdir)/config.h-vms			\
  $(srcdir)/config.in				\
  $(srcdir)/config/mh-aix			\
  $(srcdir)/config/mh-cxux7			\
  $(srcdir)/config/mh-fbsd21			\
  $(srcdir)/config/mh-openedition		\
  $(srcdir)/config/mh-windows			\
  $(srcdir)/configure				\
  $(srcdir)/configure.ac			\
  $(srcdir)/configure.com

# Construction.
DISTFILES +=					\
  $(srcdir)/Makefile.in				\
  $(srcdir)/local.mk				\
  $(srcdir)/makefile.vms			\
  $(srcdir)/testsuite/Makefile.in

# Documentation.
#
# Files listed in TEXIFILES are not prefixed by `$(srcdir)/'; use
# a replacement variable.
srcdir_TEXIFILES = $(srcdir)/fnmatch.txh $(srcdir)/pexecute.txh
DISTFILES += $(TEXISRC) $(srcdir_TEXIFILES) $(srcdir)/at-file.texi

# Scripts.
DISTFILES += $(srcdir)/maint-tool $(srcdir)/gather-docs

# Tests.
DISTFILES +=					\
  $(srcdir)/testsuite/demangle-expected		\
  $(srcdir)/testsuite/test-demangle.c		\
  $(srcdir)/testsuite/test-expandargv.c		\
  $(srcdir)/testsuite/test-pexecute.c


# The following recursive targets are missing from Libiberty's
# `Makefile.in'.

# `Makefile.in' defines `mkdir_p', not `MKDIR_P'.
MKDIR_P = $(mkdir_p)

# Copied from a `Makefile.in' generated by Automake.
distdir: $(DISTFILES)
	@srcdirstrip=`echo "$(srcdir)" | sed 's/[].[^$$\\*]/\\\\&/g'`; \
	topsrcdirstrip=`echo "$(top_srcdir)" | sed 's/[].[^$$\\*]/\\\\&/g'`; \
	list='$(DISTFILES)'; \
	  dist_files=`for file in $$list; do echo $$file; done | \
	  sed -e "s|^$$srcdirstrip/||;t" \
	      -e "s|^$$topsrcdirstrip/|$(top_builddir)/|;t"`; \
	case $$dist_files in \
	  */*) $(MKDIR_P) `echo "$$dist_files" | \
			   sed '/\//!d;s|^|$(distdir)/|;s,/[^/]*$$,,' | \
			   sort -u` ;; \
	esac; \
	for file in $$dist_files; do \
	  if test -f $$file || test -d $$file; then d=.; else d=$(srcdir); fi; \
	  if test -d $$d/$$file; then \
	    dir=`echo "/$$file" | sed -e 's,/[^/]*$$,,'`; \
	    if test -d "$(distdir)/$$file"; then \
	      find "$(distdir)/$$file" -type d ! -perm -700 -exec chmod u+rwx {} \;; \
	    fi; \
	    if test -d $(srcdir)/$$file && test $$d != $(srcdir); then \
	      cp -fpR $(srcdir)/$$file "$(distdir)$$dir" || exit 1; \
	      find "$(distdir)/$$file" -type d ! -perm -700 -exec chmod u+rwx {} \;; \
	    fi; \
	    cp -fpR $$d/$$file "$(distdir)$$dir" || exit 1; \
	  else \
	    test -f "$(distdir)/$$file" \
	    || cp -p $$d/$$file "$(distdir)/$$file" \
	    || exit 1; \
	  fi; \
	done

installdirs: # FIXME: Write me.
# Use something like this:
#
#	for dir in "$(DESTDIR)$(pyexecdir)" "$(DESTDIR)$(bindir)" "$(DESTDIR)$(pythondir)" "$(DESTDIR)$(pythondir)"; do \
#	  test -z "$$dir" || $(MKDIR_P) "$$dir"; \
#	done
#
# ?

install-dvi: # FIXME: Write me.

uninstall: # FIXME: Write me.

.PHONY: distdir installdirs install-dvi uninstall


# Targets doing nothing.
EMPTY_AUTOMAKE_TARGETS = ps install-ps install-data install-exec ctags
.PHONY: $(EMPTY_AUTOMAKE_TARGETS)
$(EMPTY_AUTOMAKE_TARGETS):
