##
## List of headers in metalic
## Include this file to have access to their name.
##

MLC_DEP =					\
  array/all.hh					\
  array/1d.hh					\
  array/1d.hxx					\
  array/2d.hh					\
  array/2d.hxx					\
  array/3d.hh					\
  array/3d.hxx					\
  array/objs.hh					\
  array/nd.hh					\
  bool.hh					\
  cmp.hh					\
  config/system.hh				\
  contract.hh					\
  is_a.hh					\
  loop.hh					\
  math.hh					\
  objs.hh					\
  optional.hh					\
  type.hh					\
  typeadj.hh
