##
## List of headers in metalic
## Include this file to have access to their name.
##

MLC_DEP =					\
  any.hh					\
  array/1d.hh					\
  array/1d.hxx					\
  array/2d.hh					\
  array/2d.hxx					\
  array/3d.hh					\
  array/3d.hxx					\
  array/all.hh					\
  array/nd.hh					\
  array/objs.hh					\
  bool.hh					\
  box.hh					\
  cmp.hh					\
  config/system.hh				\
  contract.hh					\
  is_a.hh					\
  properties.hh					\
  tracked_ptr.hh				\
  traits.hh					\
  types.hh

