
#undef OLNSAVE_PACKAGE_NAME
#undef OLNSAVE_PACKAGE_TARNAME
#undef OLNSAVE_PACKAGE_VERSION
#undef OLNSAVE_PACKAGE_STRING
#undef OLNSAVE_PACKAGE_BUGREPORT

#ifdef PACKAGE_NAME
#define OLNSAVE_PACKAGE_NAME PACKAGE_NAME
#undef PACKAGE_NAME
#endif

#ifdef PACKAGE_STRING
#define OLNSAVE_PACKAGE_STRING PACKAGE_STRING
#undef PACKAGE_STRING
#endif

#ifdef PACKAGE_VERSION
#define OLNSAVE_PACKAGE_VERSION PACKAGE_VERSION
#undef PACKAGE_VERSION
#endif

#ifdef PACKAGE_TARNAME
#define OLNSAVE_PACKAGE_TARNAME PACKAGE_TARNAME
#undef PACKAGE_TARNAME
#endif

#ifdef PACKAGE_BUGREPORT
#define OLNSAVE_PACKAGE_BUGREPORT PACKAGE_BUGREPORT
#undef PACKAGE_BUGREPORT
#endif

#include <oln/config/pconf.inc>

#define OLN_PACKAGE_NAME PACKAGE_NAME
#undef PACKAGE_NAME
#ifdef OLNSAVE_PACKAGE_NAME
#define PACKAGE_NAME OLNSAVE_PACKAGE_NAME
#undef OLNSAVE_PACKAGE_NAME
#endif

#define OLN_PACKAGE_VERSION PACKAGE_VERSION
#undef PACKAGE_VERSION
#ifdef OLNSAVE_PACKAGE_VERSION
#define PACKAGE_VERSION OLNSAVE_PACKAGE_VERSION
#undef OLNSAVE_PACKAGE_VERSION
#endif
 
#define OLN_PACKAGE_TARNAME PACKAGE_TARNAME
#undef PACKAGE_TARNAME
#ifdef OLNSAVE_PACKAGE_TARNAME
#define PACKAGE_TARNAME OLNSAVE_PACKAGE_TARNAME
#undef OLNSAVE_PACKAGE_TARNAME
#endif

#define OLN_PACKAGE_STRING PACKAGE_STRING
#undef PACKAGE_STRING
#ifdef OLNSAVE_PACKAGE_STRING
#define PACKAGE_STRING OLNSAVE_PACKAGE_STRING
#undef OLNSAVE_PACKAGE_STRING
#endif

#define OLN_PACKAGE_BUGREPORT PACKAGE_BUGREPORT
#undef PACKAGE_BUGREPORT
#ifdef OLNSAVE_PACKAGE_BUGREPORT
#define PACKAGE_BUGREPORT OLNSAVE_PACKAGE_BUGREPORT
#undef OLNSAVE_PACKAGE_BUGREPORT
#endif
