TEMPLATE	= app
LANGUAGE	= C++

INCLUDEPATH	+= .

SOURCES	+= main.cc

HEADERS	+= filterinterface.hh image_viewer.hh qtincludes.hh utils.hh

FORMS	= visualization_window.ui

######################################################################
# Automatically generated by qmake (1.07a) Wed May 25 10:08:50 2005
######################################################################


# Input
